# Generated by Django 5.0.7 on 2024-07-28 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Accounting Package', 'Accounting Package'), ('ERP', 'Enterprise Resource Planning (ERP)'), ('Payroll', 'Payroll')], max_length=50)),
                ('type', models.CharField(choices=[('Light', 'Light'), ('Heavy', 'Heavy'), ('Essential', 'Essential'), ('Plus', 'Plus'), ('Advance', 'Advance'), ('Premium', 'Premium')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_registration', models.DateField()),
                ('date_of_subscription', models.DateField()),
                ('end_of_subscription', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='DuxteSubscriptions.software')),
            ],
        ),
    ]
