# Generated by Django 5.0.7 on 2024-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_registration', models.DateField()),
                ('end_of_subscription', models.DateField()),
            ],
        ),
    ]
