# Generated by Django 5.0.7 on 2024-07-29 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='contact',
            field=models.CharField(error_messages={'blank': 'Contact cannot be blank.', 'max_length': 'Contact must be 255 characters or fewer.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='customer_name',
            field=models.CharField(error_messages={'blank': 'Customer name cannot be blank.', 'max_length': 'Customer name must be 255 characters or fewer.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_registration',
            field=models.DateField(error_messages={'blank': 'Date of registration cannot be blank.', 'invalid': 'Enter a valid date.'}),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_subscription',
            field=models.DateField(error_messages={'blank': 'Date of subscription cannot be blank.', 'invalid': 'Enter a valid date.'}),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='email1',
            field=models.EmailField(error_messages={'blank': 'Email cannot be blank.', 'invalid': 'Enter a valid email address.'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='email2',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Enter a valid email address.'}, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='end_of_subscription',
            field=models.DateField(error_messages={'blank': 'End of subscription cannot be blank.', 'invalid': 'Enter a valid date.'}),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='phone_number',
            field=models.CharField(error_messages={'blank': 'Phone number cannot be blank.', 'max_length': 'Phone number must be exactly 10 digits.'}, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='software',
            field=models.ForeignKey(blank=True, error_messages={'null': 'Software cannot be null.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='DuxteSubscriptions.software'),
        ),
    ]
