# Generated by Django 5.0.7 on 2024-07-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0002_alter_companyuser_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='last_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
