# Generated by Django 5.0.7 on 2024-09-18 06:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0003_alter_auditlog_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='base_serial_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='customer_account',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_registration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_subscription',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='email1',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='end_of_subscription',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='DuxteSubscriptions.software'),
        ),
        migrations.AlterField(
            model_name='software',
            name='addons',
            field=models.TextField(blank=True, help_text='Comma-separated addons.', null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DuxteSubscriptions.softwarecategory'),
        ),
        migrations.AlterField(
            model_name='software',
            name='editions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DuxteSubscriptions.softwareedition'),
        ),
        migrations.AlterField(
            model_name='software',
            name='versions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DuxteSubscriptions.softwareversion'),
        ),
    ]
