# Generated by Django 5.0.7 on 2024-07-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0003_companyuser_last_reminder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='last_reminder_date',
        ),
    ]
