# Generated by Django 5.0.7 on 2024-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0004_remove_companyuser_last_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
