# Generated by Django 5.0.7 on 2024-09-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0004_softwarecategory_softwareedition_softwareversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='editions',
        ),
        migrations.AddField(
            model_name='software',
            name='editions',
            field=models.ManyToManyField(to='DuxteSubscriptions.softwareedition'),
        ),
    ]
