# Generated by Django 5.0.7 on 2024-09-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0005_remove_software_editions_software_editions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='versions',
        ),
        migrations.AddField(
            model_name='software',
            name='versions',
            field=models.ManyToManyField(to='DuxteSubscriptions.softwareversion'),
        ),
    ]
