# Generated by Django 5.0.7 on 2024-09-19 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0006_remove_software_versions_software_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='software_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='DuxteSubscriptions.softwareedition'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='software_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='DuxteSubscriptions.softwareversion'),
        ),
    ]
