# Generated by Django 5.0.7 on 2024-09-23 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0007_alter_companyuser_software_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='subscription_duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in months (1 to 12 months).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
    ]
