# Generated by Django 5.0.7 on 2024-09-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0009_usercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='software',
            name='addons',
        ),
        migrations.AddField(
            model_name='software',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='softwares', to='DuxteSubscriptions.addon'),
        ),
    ]
