# Generated by Django 5.0.7 on 2024-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0010_addon_remove_software_addons_software_addons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='software_addon',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='is_subscription_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='software_addons',
            field=models.ManyToManyField(blank=True, to='DuxteSubscriptions.addon'),
        ),
    ]
