# Generated by Django 5.0.7 on 2024-09-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0011_remove_companyuser_software_addon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='software_addons',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='software_edition',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='software_version',
        ),
    ]
