# Generated by Django 5.0.7 on 2024-09-29 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0012_remove_companyuser_software_addons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='software_addons',
            field=models.ManyToManyField(blank=True, to='DuxteSubscriptions.addon'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='software_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='DuxteSubscriptions.softwareedition'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='software_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='DuxteSubscriptions.softwareversion'),
        ),
    ]
