# Generated by Django 5.0.7 on 2024-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0013_companyuser_software_addons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
