# Generated by Django 5.0.7 on 2024-10-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0014_software_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='reminder_count',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
