# Generated by Django 5.0.7 on 2024-10-10 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0015_remove_companyuser_reminder_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='last_date_of_subscription',
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='base_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='customer_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
