# Generated by Django 5.0.7 on 2024-10-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0016_remove_companyuser_last_date_of_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_registration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_subscription',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='end_of_subscription',
            field=models.DateTimeField(),
        ),
    ]
