# Generated by Django 5.0.7 on 2024-10-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0017_alter_companyuser_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_registration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='date_of_subscription',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='end_of_subscription',
            field=models.DateField(),
        ),
    ]
