# Generated by Django 5.0.7 on 2024-10-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0018_alter_companyuser_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
