# Generated by Django 5.0.7 on 2024-10-11 08:16

import DuxteSubscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0019_alter_companyuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[DuxteSubscriptions.models.validate_phone_number]),
        ),
    ]
