# Generated by Django 5.0.7 on 2024-10-11 08:19

import DuxteSubscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0020_alter_companyuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[DuxteSubscriptions.models.validate_phone_number]),
        ),
    ]
