# Generated by Django 5.0.7 on 2024-10-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuxteSubscriptions', '0021_alter_companyuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='is_subscription_valid',
        ),
    ]
