from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    # path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('create_company_user/', views.create_company_user, name='create_company_user'),
    path('software/load-editions-versions/', views.load_editions_and_versions, name='load_editions_and_versions'),
    path('company_user_list/', views.company_user_list, name='company_user_list'),
    path('company_user_list/<str:category>/', views.company_user_list, name='company_user_list_with_category'),
    path('toggle-status/<int:pk>/', views.toggle_status, name='toggle_status'),
    path('company-user-list/<str:category>/', views.company_user_list_with_category, name='company_user_list_with_category'),
    path('company_users/<int:pk>/', views.company_user_detail, name='company_user_detail'),
    path('company_users/<int:pk>/edit/', views.update_company_user, name='update_company_user'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('api/software-trends/', views.software_trends, name='software_trends'),
    path('follow-up-customers/', views.follow_up_customers, name='follow_up_customers'),
    path('active-customers/', views.active_customers, name='active_customers'),
    path('valid-customers/', views.valid_customers, name='valid_customers'),
    path('expired-customers/', views.expired_customers, name='expired_customers'),
    path('company_users/soft_delete/<int:user_id>/', views.soft_delete_user, name='soft_delete_user'),
    path('software/delete/<int:pk>/', views.soft_delete_software, name='soft_delete_software'),
    path('company_users/restore/<int:user_id>/', views.restore_user, name='restore_user'),
    path('company_users/deleted/', views.deleted_user_list, name='deleted_user_list'),
    path('add-software-category/', views.add_software_category, name='add_software_category'),
    path('add-software-edition/', views.add_software_edition, name='add_software_edition'),
    path('add-software-version/', views.add_software_version, name='add_software_version'),
    path('add_software/', views.add_software, name='add_software'),
    path('software/edit/<int:pk>/', views.edit_software, name='edit_software'),
    path('software_list/', views.software_list, name='software_list'),
    path('delete-software-category/<int:category_id>/', views.delete_software_category, name='delete_software_category'),
    path('delete-software-edition/<int:edition_id>/', views.delete_software_edition, name='delete_software_edition'),
    path('delete-software-version/<int:version_id>/', views.delete_software_version, name='delete_software_version'),
    path('edit-software-category/<int:category_id>/', views.edit_software_category, name='edit_software_category'),
    path('edit-software-edition/<int:edition_id>/', views.edit_software_edition, name='edit_software_edition'),
    path('edit-software-version/<int:version_id>/', views.edit_software_version, name='edit_software_version'),
    path('create-addon/', views.create_addon, name='create_addon'),
    path('delete-addon/<int:addon_id>/', views.delete_addon, name='delete_addon'),
    path('edit-software-addon/<int:addon_id>/', views.edit_software_addon, name='edit_software_version'),
    path('audit-logs/', views.audit_log_list, name='audit_log_list'),
    path('export-to-pdf/', views.export_to_pdf, name='export_to_pdf'),
    path('export-to-pdf/<str:category>/', views.export_to_pdf, name='export_to_pdf'),
    path('export-to-excel/<str:category>/', views.export_to_excel, name='export_to_excel'),
    path('export-to-pdf/<str:category>/', views.export_to_pdf, name='export_to_pdf_with_category'),
    path('export-to-excel/', views.export_to_excel, name='export_to_excel'),
    path('export-to-excel/<str:category>/', views.export_to_excel, name='export_to_excel_with_category'),
    path('import_template_view/', views.import_template_view, name='import_template_view'),
    path('download-company-template/', views.download_company_template, name='download_company_template'),
    path('download-software-template/', views.download_software_template, name='download_software_template'),
    path('import-users/', views.import_users, name='import_users'),
    path('import-software/', views.import_software, name='import_software_view'),
    path('change-password/', views.change_password, name='change_password'),

]

